[tool.isort]
profile = "black"
src_paths = ["src", "main.py"]

[tool.black]

[tool.mypy]
exclude = ["venv"]
check_untyped_defs = true
ignore_missing_imports = true
disallow_any_explicit = false
implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_no_return = true
warn_unreachable = true
ignore_errors = false
allow_untyped_globals = false
allow_redefinition = false
local_partial_types = true
implicit_reexport = true
strict_concatenate = true
strict_equality = true
show_error_context = true
show_column_numbers = true
hide_error_codes = false
pretty = true
color_output = true
error_summary = true
show_absolute_path = false
incremental = true

[tool.pytest]
testpaths = "tests"
